### ISSUE TITLE
Sign in page 

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#2]
When selecting to sign in with email the keyboard pop up covers the test bix for the email address

**Comment by quotestream** [comment]
I've reproduced this successfully.. working on a fix

**Comment by quotestream** [comment]
Fixed in 0.5.0

![screen shot 2018-10-18 at 3 06 09 pm](https://user-images.githubusercontent.com/41097502/47177870-ab6b1480-d2e7-11e8-9f51-92360e82e89c.png)
