### ISSUE TITLE
Email validation not working

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#22]
Email validation not working And cannot bypass

**Comment by amlew00** [comment]
![48309319-08ce-446f-87f4-0fb5619999ba](https://user-images.githubusercontent.com/44245093/48431597-115c8780-e740-11e8-9098-57b3ed5d04ae.png)

**Comment by quotestream** [comment]
thanks for reporting it

**Comment by quotestream** [comment]
fixed, should work on any build
