### ISSUE TITLE
Error accessing contacts 

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#31]
Error while accessing contacts

**Comment by amlew00** [comment]
![06a05cb0-d997-49e8-a4d3-f93e431d25a7](https://user-images.githubusercontent.com/44245093/49114745-f5d89d00-f266-11e8-8ecb-de0281e32eb9.png)

**Comment by amlew00** [comment]
Still a little buggy when tapping the friends icon. Sometimes closing and reopening clears it, sometimes need to log out and back in, when it fails it gives the image above

**Comment by quotestream** [comment]
I revamped the contacts code in 0.9.1 and have not been able to reproduce this
