### ISSUE TITLE
Strange characters 

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#32]
Strange chatacters when sharing to FB messenger and email

**Comment by amlew00** [comment]
![c6a7e733-1957-4b6a-a2af-85ea1074f144](https://user-images.githubusercontent.com/44245093/49115308-75b33700-f268-11e8-96f7-35fe49aa219b.png)

**Comment by amlew00** [comment]
![c8a82a83-ec4b-49c9-9774-e6e730604eed](https://user-images.githubusercontent.com/44245093/49160411-b3f63800-f2f4-11e8-9652-aa27c4e0d7ac.png)

**Comment by amlew00** [comment]
This might actually be a font issue... it is also showing in my stream

**Comment by amlew00** [comment]
![9df8085c-915b-4463-9cc6-9a681f45267e](https://user-images.githubusercontent.com/44245093/49160656-3e3e9c00-f2f5-11e8-99d3-1266e5e71593.png)

**Comment by quotestream** [comment]
I think I fixed it in 0.9.1
