### ISSUE TITLE
Background pictures not loading

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#8]
There is the ability to load your own photo from your camera roll, however it doesnt save or show in the preview

**Comment by quotestream** [comment]
able to reproduce.. working on a fix

**Comment by quotestream** [comment]
fixed in 0.5.0

![screen shot 2018-10-18 at 3 56 51 pm](https://user-images.githubusercontent.com/41097502/47180418-8e860f80-d2ee-11e8-801f-611eca4e6010.png)
