### ISSUE TITLE
failure while trying to share

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#9]
Failure message while trying to share. I will text you the screen shot.

**Comment by amlew00** [comment]
![d320c800-fc21-4755-8bfd-9d58c47ff098](https://user-images.githubusercontent.com/44245093/47175016-39430180-d2e0-11e8-8b63-552341d83b88.png)

**Comment by quotestream** [comment]
I was able to reproduce... debugging

**Comment by quotestream** [comment]
fixed in 0.5.0

![screen shot 2018-10-18 at 4 30 38 pm](https://user-images.githubusercontent.com/41097502/47182388-4c130180-d2f3-11e8-8929-2787c8d38e1c.png)
